MonPremierSiteDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('firstApp/', include('firstApp.urls')),
    path('admin/', admin.site.urls),
]

firstApp/urls.py
from django.urls import path

from . import views

app_name = 'firstApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

firstApp/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

firstApp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'firstApp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'firstApp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'firstApp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'firstApp/detail.html', {
            'question': question,
            'error_message': "Vous avez rien selectionner.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('firstApp:results', args=(question.id,)))

firstApp/templates/firstApp/detail.html
{% include 'firstApp/header.html' %}

<form class="form" action="{% url 'firstApp:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1 class="legend">{{ question.question_text }}</h1>
        {% if error_message %}<p class="error-message"><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <div class="choice">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label class="test" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            </div>
        {% endfor %}
    </fieldset>
    <input class="btn btn-soumettre" type="submit" value="Soumettre">
</form>

{% include 'firstApp/footer.html' %}

firstApp/templates/firstApp/footer.html
<div class="footer-large">
    <a class="btn-admin" href="/admin/">Admin Panel</a>
    <p class="white-text">Créer par Frédérick Perazzelli-Delorme et Jean-Nyckolas Roy</p>
</div>

</body>

firstApp/templates/firstApp/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'firstApp/style.css' %}">

<body>

<div class="header-large">
    <img class="large-banner" src="{% static 'firstApp/image/survey.png' %}" alt="My image">
</div>

firstApp/templates/firstApp/index.html
{% include 'firstApp/header.html' %}

<div class="large-header">
    <h1 class="center-h1"> Liste des sondages </h1>
</div>

{% if latest_question_list %}
    <div class="container-sondage">
        {% for question in latest_question_list %}
            <div class="tile-sondage">
                <a class="question" href="{% url 'firstApp:detail' question.id %}">{{ question.question_text }}</a>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>Aucun sondage disponible.</p>
{% endif %}


{% include 'firstApp/footer.html' %}

firstApp/templates/firstApp/results.html
{% include 'firstApp/header.html' %}

<div class="large-header">
    <h1 class="center-h1">{{ question.question_text }}</h1>
</div>

<div class="container-sondage">
    {% for choice in question.choice_set.all %}
        <div class="tile-sondage">
            <p class="question">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
        </div>
    {% endfor %}

    <a class="btn btn-details" href="{% url 'firstApp:detail' question.id %}">Votez de nouveau ?</a>
    <a class="btn btn-question" href="{% url 'firstApp:index' %}">Retour aux questions</a>

</div>


{% include 'firstApp/footer.html' %}